Исправление ошибок
penicilllia/test-guru pull request #1
Opened 2021-01-31 05:01 UTC by penicilllia

2021-02-01 06:52 UTC, BubuntuClu requested changes

2021-02-01 06:52 UTC, BubuntuClu commented on app/controllers/about_controller.rb
>  class AboutController < ApplicationController
контроллер не нужен в этом задании, надо удалить

2021-02-01 06:52 UTC, BubuntuClu commented on config/application.rb
> +    VERSION = '1.0.0'
вынеси это в отдельный файл - version.rb. сделай так что бы это была не глобальная константа. давай получать ее таким образом `TestGuru.version`

2021-02-01 06:52 UTC, BubuntuClu commented on config/application.rb
>      config.i18n.available_locales = [:en, :rus]
`:ru`

2021-02-01 06:52 UTC, BubuntuClu commented on public/about/author.html
> +  <br><p><a href="https://github.com/penicilllia">Ссылка на git страницу автора</a></p>
ссылки на сторонние ресурсы открываем в новой вкладке

2021-02-01 06:52 UTC, BubuntuClu commented on public/about.html
>    Проект предназначен для:
ссылки на сторонние ресурсы открываем в новой вкладке

2021-02-01 06:52 UTC, BubuntuClu commented on config/application.rb
> +    VERSION = '1.0.0'
и почему версия начинается с 100? у тебя еще нет релизной версии

2021-02-01 06:52 UTC, BubuntuClu commented on app/controllers/about_controller.rb
>  class AboutController < ApplicationController
вероятно есть и роуты с вьюхами их тоже надо удалить

2021-02-01 18:36 UTC, BubuntuClu requested changes

2021-02-01 18:36 UTC, BubuntuClu commented on config/application.rb
> +    config.i18n.available_locales = [:rus]
`config.i18n.available_locales = [:en, :ru]` как то не так ты восприняла замечание

2021-02-01 18:36 UTC, BubuntuClu commented on config/initializers/version.rb
> +@version = '0.0.1'
это до сих пор глобальная переменная. она ничем не "окружена". и мы вроде договорилсь о методе получения версии приложения через команду `TestGuru.version` в консоле. так же с версией ты о5 не угадала. в доке написано с какой версии начинается приложение

2021-02-01 18:36 UTC, BubuntuClu commented on public/about.html
>    Проект предназначен для:
ничего не изменилось

2021-02-01 18:36 UTC, BubuntuClu commented on public/about/author.html
> +  <br><p><a href="https://github.com/penicilllia">Ссылка на git страницу автора</a></p>
и тут тоже. надо еще опцию добавить к тэгу `a`

2021-02-04 16:26 UTC, penicilllia commented on public/about.html
>    Проект предназначен для:
> ссылки на сторонние ресурсы открываем в новой вкладке
Но они и так открываются в новой вкладке. Там же прописан  <base target="_blank">

2021-02-05 19:13 UTC, BubuntuClu commented on config/initializers/version.rb
> +  def TestGuru.version
def TestGuru.version

странная запись. это почему так сделано?

2021-02-06 06:06 UTC, merged