Задание по интерфейсу запросов ActiveRecord
penicilllia/test-guru pull request #3
Opened 2021-02-19 09:29 UTC by penicilllia

2021-02-19 18:49 UTC, BubuntuClu requested changes

2021-02-19 18:49 UTC, BubuntuClu commented on app/models/test.rb
> +    test.where(category_name :category.name).reverse_order
что такое `test` откуда он берется?
`category_name :category.name` этот синтаксис не валидный.
`reverse_order` относительно чего будет сделан реверс?

проверяй свой код в консоле - `rails с`

2021-02-19 18:49 UTC, BubuntuClu commented on app/models/user.rb
> +    user_tests.where(user.id :user_tests.user_id AND test_level :user_tests.test.level)
что за `user_tests`?

2021-02-19 18:49 UTC, BubuntuClu commented on app/models/user.rb
> +    user_tests.where(user.id :user_tests.user_id AND test_level :user_tests.test.level)
`(user.id :user_tests.user_id AND test_level :user_tests.test.level)` - этот синтаксис невалидный

2021-02-19 18:49 UTC, BubuntuClu commented on db/migrate/20210211173510_create_tests.rb
> +      t.belongs_to :user_tests, index: true, foreign_key: true
так делать нельзя. смерженные миграции нельзя править. если что-то надо добавить в таблицу, то только через новые миграции.
этот код надо удалить и создать отдельную миграцию на добавление этой связи

2021-02-19 18:49 UTC, BubuntuClu commented on db/migrate/20210211173926_create_users.rb
> +      t.belongs_to :user_tests, index: true, foreign_key: true
так делать нельзя. смерженные миграции нельзя править. если что-то надо добавить в таблицу, то только через новые миграции.
этот код надо удалить и создать отдельную миграцию на добавление этой связи

2021-02-19 18:49 UTC, BubuntuClu commented on db/migrate/20210211173926_create_users.rb
> +      t.references :test, foreign_key: true
эта связь зачем? почему тут `references`, а выше `belongs_to`?

2021-02-19 18:49 UTC, BubuntuClu commented on db/seeds.rb
> +tests = Test.create([ {title: 'Ruby', level: 1}, {title: 'RoR', level: 2}, {title: 'C', level: 2}, {title: 'Ruby', level: 3} ])
тесты должны принадлежать какой-то категории

2021-02-19 18:49 UTC, BubuntuClu commented on db/seeds.rb
> +questions = Question.create([ {body: "Под влиянием какого языка был создан Ruby?"}, {body: "Как называется самый популярный фреймворк на Ruby?"}, \
вопрос должен быть привязан к тесту

2021-02-19 18:49 UTC, BubuntuClu commented on db/seeds.rb
> +answers = Answer.create([ {body: "Под влиянием Perl"}, {body: "Ruby on Rails"}, {body: "Puma, Unicorn, Passenger"}, {body: "Абстракция, инкапсуляция, наследование, полиморфизм."}, \
ответы должны принадлежать вопросу

2021-02-23 15:42 UTC, BubuntuClu requested changes

2021-02-23 15:42 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.test_list(ctegory_name)
ctegory_name - очепятка

2021-02-23 15:42 UTC, BubuntuClu commented on app/models/test.rb
> +    tests.where(category_name :category.name).order('id DESC')
что такое `tests` в этом методе?
 (category_name :category.name) - не валидный руби код. посмотри как формируются запросы в AR

2021-02-23 15:42 UTC, BubuntuClu commented on app/models/user.rb
> +    users.where("level = test_level AND user_id = test_id")
`users` что это? откуда берется?

where("level = test_level AND user_id = test_id") сюда никакие значения не будут подставлены. такое выражение и будет в SQL передано, а тебе надо сюда передать уровень и пользователя

2021-02-23 15:42 UTC, BubuntuClu commented on app/models/user.rb
> +    users.where("level = test_level AND user_id = test_id")
user_id = test_id - что значит это условие? почему пользователь должен равнятся тесту?

2021-02-23 15:42 UTC, BubuntuClu commented on app/models/user_test.rb
> +  has_many :users, :class_name => "User"
зачем тут опция `class_name`?

2021-02-23 15:42 UTC, BubuntuClu commented on app/models/user_test.rb
> +  has_many :tests, :class_name => "Test"
и тут

2021-02-23 15:42 UTC, BubuntuClu commented on db/schema.rb
> +  create_table "tests_users", id: false, force: :cascade do |t|
эта таблица тебе нужна? она не используется в коде

2021-02-28 12:38 UTC, BubuntuClu requested changes

2021-02-28 12:38 UTC, BubuntuClu commented on db/migrate/20210228070218_remove_table_user_tests.rb
> +class RemoveTableUserTests < ActiveRecord::Migration[5.2]
Для чего эта миграция? Ты удаляешь таблицу, а потом ее создаёшь. В чем смысл?

2021-02-28 12:38 UTC, BubuntuClu commented on db/schema.rb
> +  create_table "tests_users", id: false, force: :cascade do |t|
Эта таблица ещё осталась, но ее использования не добавилось. Ее удалить надо

2021-03-11 06:30 UTC, penicilllia reviewed
4 задание

2021-03-11 06:31 UTC, merged